### PR TITLE
github docstring

### PR DESCRIPTION
**Pull request by Shreya111111**
Issue #270  @nikhil25803  added github docstring to all the classes ..plz check

### CODE REVIEW

**Comment by Shreya111111** [comment]
Issue #270 and PR #326  @nikhil25803  kindly check the assigned one

**Review by nikhil25803 — APPROVED** [review]
Great work !!!

**Comment by nikhil25803** [comment]
Great work @Shreya111111 !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Comment by Shreya111111** [comment]
@nikhil25803 Thanks for explaining my mistake which I did earlier. I learned a lot .

**Comment by nikhil25803** [comment]
It was a great experience for me as well, hope to see more contributions from your side.

**Pull request merged**
