### PR TITLE
Added Flyrobu and Robu search

### PR DESCRIPTION
**Pull request by WhoIsJayD**
## Description

> The new flyrobu scraper will retrieve all the items from site with title, price, brand name, image url, description, rating, model id and link

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

Flyrobu:
image

Robu:
image

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by WhoIsJayD** [comment]
@nikhil25803 Please look into my pull request.

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Hey @WhoIsJayD | Improve documentation as suggested. 

Will review the rest of the code further.

**Comment by WhoIsJayD** [comment]
Ig there should be no issue now

**Comment by WhoIsJayD** [comment]
> Please format the docstring as shown in the image below. With proper class name, method and sample return type. image

@nikhil25803 please check this now.

**Review by nikhil25803 — APPROVED** [review]

**Pull request merged**
