### PR TITLE
mkdocs updates with modules

### PR DESCRIPTION
**Pull request by adishgarg**
## Description

- all the modules mentioned in `documentation.md` added 
- search feature updated
- file formatted accordingly

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

image

## Additional Notes/Comments

-  The modules that were added before hand from `dev-documentation.md` and were not present in `documentation.md` have not been removed from `modules` but have been commented out in `mkdocs.yml` hence will not appear in the documentation.

- I have added a `Guide` page which contains the example usage and a link to the module in the documentation, like 
`- [GitHub](modules/github.md)`. If necessary, I i will add the link to the respective repositories

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by adishgarg** [comment]
the documentation for Github Education is missing in `dev-documentation.md` should i fix that as well?

**Comment by adishgarg** [comment]
Resolves #1036

**Comment by adishgarg** [comment]
closes #1036

**Comment by nikhil25803** [comment]
Great work @adishgarg  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Pull request merged**
