### PR TITLE
flipkart scraping of mobile phone under 50k

### PR DESCRIPTION
**Pull request by Sushilverma002**
## Description

> The changes made in this pull request should be briefly described.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [yes ] Have you adhered to the repository's defined coding convention rules?
- [yes ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ yes] Have you sent a message along with the result or response?
- [yes ] Have you used the try-catch technique?
- [yes ] Has the method/class been added to the documentation (md file)?

## Screenshots

>
image
.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Need a few changes from your side @Sushilverma002 |
1. Do not use packages like Pandas, we do not need to download the result as a csv or any file.
2. Output the returned value as a response to the user (check other modules and classes to see how things are implemented and integrated all together)
3. The `Flipkart` class has already been initiated, check [here](https://github.com/Clueless-Community/scrape-up/blob/main/src/scrape_up/flipkart/flipkart_file.py). Add your method to this same class only instead creating a new file

**Comment by Sushilverma002** [comment]
@nikhil25803 have a look now.

**Comment by Sushilverma002** [comment]
image
now it showing proper output.
i choose for scraping mobile phone under ke 50k as seeing Indian market most of the people have their budget under 50k so i choose do scrap this and one more thing all phone a their like top to lowest.

**Comment by Sushilverma002** [comment]
@nikhil25803 please have look !!!!!!!

**Comment by Sushilverma002** [comment]
@nikhil25803 please respond

**Review by nikhil25803 — APPROVED** [review]
Changes approved |

**Comment by nikhil25803** [comment]
Great work @Sushilverma002 !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Pull request merged**
