### PR TITLE
#35 added achievements

### PR DESCRIPTION
**Pull request by Viveksati5143**
added achievements of a user

### CODE REVIEW

**Comment by Viveksati5143** [comment]
@nikhil25803 can we please review and merge it.

**Comment by nikhil25803** [comment]
Include the method in `documentation.md` file and also upload a screenshot demonstrating that the method is working fine @Viveksati5143

**Comment by nikhil25803** [comment]
Any update @Viveksati5143?

**Comment by Viveksati5143** [comment]
Is it mandat to upload a ss coz my system ran into problem and I'll take time fixing it

**Comment by Viveksati5143** [comment]
@nikhil25803 should i Include the method in documentation.md file is it fine?

**Comment by nikhil25803** [comment]
> @nikhil25803 should i Include the method in documentation.md file is it fine?

Yes, add it in the `documentation.md` file.

**Comment by Viveksati5143** [comment]
@nikhil25803 add JWOC tag

**Pull request merged**
