### PR TITLE
Fixes issue #883 typing errors in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Suhani2**
## Description

> In the "Let's say you want to scrape the avatar URL of and user" line, the "and" is replaced with "a"

Also, the "steps applying which we can do this" is changed  to "The steps to apply in order to achieve this are as follows:".

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ ] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

As I am new to the open source contributions I would appreciate guidance and recommendations in my contributions.  

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by iamanolive** [comment]
hi, i had created an issue for these exact errors yesterday (https://github.com/Clueless-Community/scrape-up/issues/883), and i don't think it's fair to solve them without being assigned first. you're supposed to get the issues on a first-come-first-serve basis.

**Comment by Suhani2** [comment]
@iamanolive sorry, I had no idea we have to be assigned to an issue. I am new to this.

**Comment by iamanolive** [comment]
> @iamanolive sorry, I had no idea we have to be assigned to an issue. I am new to this.

@Suhani2 no it's completely alright!!

**Comment by nikhil25803** [comment]
As @iamanolive does not have any issue with it, merging this PR.

Great work @Suhani2  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Pull request merged**
