### PR TITLE
testCase updated

### PR DESCRIPTION
**Pull request by Laxmankohar**

### CODE REVIEW

**Comment by nikhil25803** [comment]
+ These are the private methods, are they still callable?

image

**Comment by Laxmankohar** [comment]
No, They are giving error.

image

**Comment by nikhil25803** [comment]
Remove them, they are not meant to be call.

**Comment by Laxmankohar** [comment]
ok

**Comment by Laxmankohar** [comment]
Check this and confirm it. sothat i can commit again

image

**Comment by nikhil25803** [comment]
Commit this change @Laxmankohar :))

**Comment by Laxmankohar** [comment]
> Commit this change @Laxmankohar :))

Done

**Pull request merged**
