### PR TITLE
Added new features to LeetCode Scraper module

### PR DESCRIPTION
**Pull request by akshaypatel67**
## Description
Added new features to leetcode module.

> get_problems_solved(): get total problems solved for username
> get_solved_by_difficulty(): get difficulty wise problems solved for username
> get_github_link(): get github link for username
> get_linkedin_link(): get linkedin link for username
> get_community_stats(): get community stats for username

> get_problems(): get list of problems by filters
> get_contests(): get upcoming contest details
> get_daily_challenge(): get daily challenge details

## Resolves: Issue #341

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Hey, this raise errors
image

Please try implementing it using `bs4`

**Comment by akshaypatel67** [comment]
Hey @nikhil25803, for scraping webpage I am using bs4 only. But for getting the data from url, I used selenium as the page has dynamic content which sometimes is missed when using requests.

But now I think it should work as I have added webdriver_manager which will install chromedriver if not already present.
Please check.

**Comment by nikhil25803** [comment]
Great work @akshaypatel67 !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Review by nikhil25803 — COMMENTED** [review]
Changes approved

**Pull request merged**
