### PR TITLE
Resolved the bug in instagram submodule

### PR DESCRIPTION
**Pull request by karthikbhandary2**
## Description

> The changes made in this pull request should be briefly described.

Previously the Instagram module used beautiful soup to scrape the user data from the meta tag of the website. It's been observed that the meta tag has some discrepancies due to which accurate information was not able to be retrieved. I made the whole submodule (more like the user.py) from scratch using Selenium. I went with selenium because it was not possible with beautiful soup. I created a single function instead of 3 separate functions. This function gets all the data i.e. followers, following, and posts. This should work since Im directly getting the data from the span tag. 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [ ] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

## Screenshots

> Uploading a screenshot illustrating the approach you developed for validation is required.

scrape output

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

If it is showing "page not available" please try to clear the cache and then try running it.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by karthikbhandary2** [comment]
Hey @nikhil25803 can you add the gssoc label to this repo?

**Comment by karthikbhandary2** [comment]
Hey @nikhil25803 Can I know how a level is fixed for a pr? I had to make this thing work from scratch and had to spend a lot of time on this. Can you reconsider the level if possible?

**Comment by nikhil25803** [comment]
Its upon me @karthikbhandary2

**Comment by karthikbhandary2** [comment]
oh ok @nikhil25803 understood thanks for letting me know

**Comment by karthikbhandary2** [comment]
so its going to be level2?

**Comment by nikhil25803** [comment]
Yes @karthikbhandary2

**Pull request merged**
