### PR TITLE
Resolved the issue in Finance submodule #268

### PR DESCRIPTION
**Pull request by karthikbhandary2**
I have resolved the bug which was in the finance sub-module. Please take a look and let me know if there are any changes needed.

### CODE REVIEW

**Comment by nikhil25803** [comment]
Changes you made still not working. For the finance class, the PR has already been made for the finance class issue #283 | So merging that one, you do focus on the Instagram issue.

**Comment by karthikbhandary2** [comment]
then this issue got resolved? I don't need to work on this?

**Comment by nikhil25803** [comment]
No @karthikbhandary2, work on the Instagram module for now.

**Comment by karthikbhandary2** [comment]
ok!

**Pull request closed without merging**
