### PR TITLE
Improved Hashnode scraper with featured and recent blogs

### PR DESCRIPTION
**Pull request by Mihan786Chistie**
## Description

> Improved hashnode scraper with featured and recent blogs

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by nikhil25803** [comment]
Great work @Mihan786Chistie !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Comment by nikhil25803** [comment]
@Mihan786Chistie | `get_feed()` is not working as well, can you check and fix it?

**Comment by Mihan786Chistie** [comment]
> @Mihan786Chistie | `get_feed()` is not working as well, can you check and fix it?

I created an issue for that I will fix it

**Comment by Mihan786Chistie** [comment]
@nikhil25803 do add the level tag for gssoc

**Pull request merged**
