### PR TITLE
Add workflow run to check code formatting

### PR DESCRIPTION
**Pull request by MannuVilasara**
## Description

> - Add worflow run to check code formatting.
>  - Also added the dependencies to format the code (black formatter).
>   - Updated the documentation.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

> image

## Additional Notes/Comments

> Formatting make it easy for contributors to explore code

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
There are too many changes added in the PR.
Only add `lint.yml` and remove all the other changes.

image

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Looks like the job failed for some reason, please look into it.

image

**Comment by MannuVilasara** [comment]
the failing is due to the formatting

**Comment by MannuVilasara** [comment]
It should pass the checks now

**Comment by nikhil25803** [comment]
Again all the extra files are added @MannuVilasara, remove it.

**Comment by MannuVilasara** [comment]
It will fail the checks if I remove that commit. Actually there is no change in the code its just formatted code.

**Comment by MannuVilasara** [comment]
removed the last commit but job will fail again

**Comment by MannuVilasara** [comment]
@nikhil25803 Should I format the code as mentioned in the job
image

**Pull request closed without merging**
