### PR TITLE
Added Test File for GitHub Scrapper

### PR DESCRIPTION
**Pull request by HavokSahil**
## Description

> Added a test File for GitHub

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you sent a message along with the result or response?

## Screenshots

image

## Additional Notes/Comments

> I found 10 methods of the GitHub modules not working properly and one of them freezes
---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Hey @HavokSahil 
Few test cases return error, check if something wrong from your side otherwise please raise an issue for them so that it can get fixed.

**Comment by HavokSahil** [comment]
@nikhil25803 I have found some bugs in the code. See issue #868 .

## The test works fine after fixing the bug
see image
Screenshot from 2023-12-22 15-42-38

Also I have fixed the bugs in the latest commit.

**Review by nikhil25803 — APPROVED** [review]

**Comment by HavokSahil** [comment]
@nikhil25803  I didn't got any points for those issues? 
Username: havoksahil
Codepeak Contributor

**Comment by nikhil25803** [comment]
I have added labels top both PR and Issue @HavokSahil, hopefully, you'll get the points till next leaderboard update.

**Pull request merged**
