### PR TITLE
Scrape up Flipkart Website

### PR DESCRIPTION
**Pull request by Tisha6661**
## Description
Scraped flipkart website for products, and bestseller products.

## Resolves: [Issue Number]
#361 

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots
image
image

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Review by nikhil25803 — APPROVED** [review]
Looks Good :))

**Comment by nikhil25803** [comment]
Great work @Tisha6661 !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Comment by Tisha6661** [comment]
@nikhil25803 I did not get points for this project, Could you please add labels to make it count for getting points. Please look into it.

**Comment by nikhil25803** [comment]
Added it @Tisha6661

**Pull request merged**
