### PR TITLE
Added Ask ubuntu scraper

### PR DESCRIPTION
**Pull request by Mihan786Chistie**
## Description

> The askUbuntu scraper will retrieve various details from the ask Ubuntu website, including questions, views, votes, answer counts, and descriptions in JSON format.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

json_valid_result

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by nikhil25803** [comment]
Great work @Mihan786Chistie  !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Comment by Mihan786Chistie** [comment]
> Great work @Mihan786Chistie  !!
> Do not forget to
> + Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
> + Give this repository a star ✨
> + Follow Clueless Community on GitHub ✅

Sure, thanks a lot for the merge😃

**Comment by Mihan786Chistie** [comment]
Hey @nikhil25803, the test folder seems to be deleted from the repository from my PR, I don't remember deleting it. Should I restore it?

**Comment by nikhil25803** [comment]
I deleted it @Mihan786Chistie

**Comment by Mihan786Chistie** [comment]
> I deleted it @Mihan786Chistie 

Is the test folder not required? @nikhil25803

**Pull request merged**
