### PR TITLE
Improved askUbuntu scraper with new, active, unanswered, bountied, frequent and high scored questions

### PR DESCRIPTION
**Pull request by Mihan786Chistie**
## Description

> Improved askUbuntu scraper with new, active, unanswered, bountied, frequent and high scored questions

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by nikhil25803** [comment]
You are doing great @Mihan786Chistie | A lot of good and clean changes✨

**Comment by Mihan786Chistie** [comment]
> You are doing great @Mihan786Chistie | A lot of good and clean changes✨
> 

Thank you so much😊

**Review by Mihan786Chistie — COMMENTED** [review]
@nikhil25803 I don't think the lines 357 and 358 are required.

**Comment by nikhil25803** [comment]
Nothing much to bother, leave it.

**Pull request merged**
