### PR TITLE
Testing academia

### PR DESCRIPTION
**Pull request by Vishal-Padia**
## Description

Wrote tests for the academia function.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

All tests passed

## Additional Notes/Comments
NA

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Hey @Vishal-Padia, you are not assigned to upload test files for `The IMDB` module, please remove that file from this PR and also the changes you made for `attribute error` in the IMDB module are already merged, remove that as well from this PR.

Else, the PR looks good :))

**Comment by nikhil25803** [comment]
Any update @Vishal-Padia?

**Comment by Vishal-Padia** [comment]
Will be pushing it within an hour

**Comment by Vishal-Padia** [comment]
okay, it is done @nikhil25803

**Comment by Vishal-Padia** [comment]
@nikhil25803 any update on this?

**Review by nikhil25803 — APPROVED** [review]

**Comment by nikhil25803** [comment]
Great work @Vishal-Padia !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Pull request merged**
