### PR TITLE
Added method to pull all Issues in a Repository

### LINKED ISSUE #41: Issues opened in a repository.
## Proposed Method:
`.issues_count()`

### Description
Create a method to get the number of issues opened in a repository.

## To what class it belongs?:
`Repository`

### PR DESCRIPTION
**Pull request by pooranjoyb**
## Methods Used :
`.__scrap_issues_page()` `.issues_count()` 

## Description
The method has been created to get the number of issues opened in a repository.

### Workflow : 
- Scraped the issues page using a method called `.__scrap_issues_page()`
- then searched the elements with issues in a method called `.issues_count()`
- iterated over each of them and returned the list of `allIssues`

## To what class it belongs?:
`Repository`

### Would be grateful if you could add the label of JWOC '23 if this PR is merged. @nikhil25803

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey @pooranjoyb, we will be including this in another class. We are planning to create a separate class for issues, where we will scrape the data from the issues page.  So I cant accept it rn :))

**Comment by nikhil25803** [comment]
What I asked to scrape is the issues count. For example in this image, there are 8 issues open.  So scrape this one.


image

**Comment by pooranjoyb** [comment]
LoL I guess I misunderstood :/ @nikhil25803

**Comment by nikhil25803** [comment]
No issue @pooranjoyb :))

**Pull request closed without merging**
