### PR TITLE
Wiki

### PR DESCRIPTION
**Pull request by metflekx**
as discussed in issue #748 ;
at `/src/scrape_up/wikipedia` i wrote the new scraper for wikipedia, to avoid overriding the previous code, i made a new file `wiki.py`. 

once the class Wiki  is instantiated, it will scrape the wikipedia page related to the query that is passed as argument to the constructor.
the class then stores a soup object that contains the html of the wikipedia page.
the method `define()` returns the definition of the query from wikipedia as string.
run the file to see the results of the test that i provided.

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
The scrapper works fine, but you do not have a method to get featured articles. Add method that can be imported by someone to scrape data and also return them in  a proper format.

Add methods like getting featured articles, or even if you are scraping a page only based on the query, return it as a response in proper format.

**Comment by metflekx** [comment]
so, let me clearify.

firstly you want the scraper method to be public and return a soup,
and then how about i make it so that the following code will return featured articles from the main page ?

```
wiki = Wiki().featured()
```

**Comment by nikhil25803** [comment]
Yes, and do not just return the soup. Instead, return them in a proper format (list of `dict` preferably).
Go through other modules, (like `github`) and see how things work.

**Comment by metflekx** [comment]
ok, how about this.
now i only added my new changes to the `wikipedia.py` which already existed before i began to work on it.
it already had methods that satisfies your constraints.  
the private __scrape() method now returns a soup ( not formatted ) but public method scrape() returns the formatted page like before.
if you think having private scraper __scrape() is not good i could rewrite the define method to use formatted page from scrape().

**Pull request closed without merging**
