### PR TITLE
Implemented BCC News scraping module

### PR DESCRIPTION
**Pull request by Nancy248**
## Description
Implemented BCC news scraping through python by using request and beautifulsoup module 
> The changes made in this pull request should be briefly described.

## Resolves: [262]

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---
I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by nikhil25803** [comment]
There's no file uploaded with the PR @Nancy248

**Comment by Nancy248** [comment]
https://github.com/Nancy248/scrape-up/upload/main#:~:text=choose%20your%20files-,mmm.py,-Commit%20changes

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
Cross check once 
image

**Comment by nikhil25803** [comment]
Hey @Nancy248 | Any update eon this PR?

**Pull request merged**
