### PR TITLE
FEAT : add lichess module and update documentation

### PR DESCRIPTION
**Pull request by msabry1**
## Description

> The changes made in this pull request should be briefly described.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [yes] Have you adhered to the repository's defined coding convention rules?
- [yes] Have you updated the 'documentation.md' file with the method/function documentation?
- [yes] Have you sent a message along with the result or response?
- [yes] Have you used the try-catch technique?
- [yes] Has the method/class been added to the documentation (md file)?

## Screenshots

image

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.

### CODE REVIEW

**Comment by msabry1** [comment]
Can you review this changes @nikhil25803 ?

**Comment by msabry1** [comment]
HI @nikhil25803 you can review and see changes now

**Comment by msabry1** [comment]
@nikhil25803 can you rereview bro ?

**Comment by nikhil25803** [comment]
Resolve the conflicts

**Comment by msabry1** [comment]
done solved @nikhil25803

**Comment by nikhil25803** [comment]
Great work @msabry1  !!
Do not forget to
+ Share your contribution on socials and tag Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Pull request merged**
