### PR TITLE
Amazon India Scraper Support [Gssoc'23] #203

### PR DESCRIPTION
**Pull request by paritoshtripathi935**
# Pull Request - Amazon India Scraper Support [Gssoc'23] #203

## Description

This pull request adds the AmazonScraper class, which enables scraping product information from Amazon based on a specified product category. The class provides methods to retrieve product URLs, scrape product details, and store the scraped data in a specified format. The implementation adheres to the requirements and conventions outlined in the project's documentation.

## Changes Made

- Added the AmazonScraper class with methods for retrieving product URLs, scraping product details, and storing the scraped data.
- Implemented error handling and fallback mechanisms for handling exceptions during scraping.
- Added unit tests to validate the functionality of the class and ensure proper data retrieval and storage.
- Ability to retrieve product URLs for a given keyword and page number from Amazon.
- Scraping of product details including SKU, name, description, image path, category, price, and timestamp.
- Support for storing the scraped data in a CSV format and json format.
- Multithreaded scraping for improved efficiency.
- Integration with Selenium for handling dynamic web pages.

## Testing

- Wrote unit tests for the AmazonScraper class to validate the functionality of key methods.

## Known Issues
- None

## Reviewer Notes

- Please review the implementation and provide feedback on the code structure, logic, and adherence to best practices.
Verify that all unit tests pass successfully.

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey, @paritoshtripathi935. Great effort, do not use any other library than bs4 or BeautifulSoup, it is light weight and easily accessible too.

Also, we don't want more dependencies, so please look into it. Do it with `bs4` only, it won't take more time as well.

**Comment by paritoshtripathi935** [comment]
@nikhil25803 thanks noted will do except for selenium and lxml. i want to use lxml so i can use xpaths to get attributes, its reliable way to get data and i need selenium in case blocking happens which do happens. 

should i remove lxml and shift to bs4?

**Comment by nikhil25803** [comment]
Yes @paritoshtripathi935

**Comment by paritoshtripathi935** [comment]
okay @nikhil25803 on it

**Comment by paritoshtripathi935** [comment]
hey @nikhil25803 i have been working on removing lxml but bs4 doesn't support XPath selectors. xpath are best are beacause of high accuracy and low maintenance . I think we should keep lxml it will provide better output.

**Comment by nikhil25803** [comment]
Still @paritoshtripathi935, you are using plenty of other libraries (like `pandas`)which is not possible to merge, this will make the package comparatively heavy.

**Comment by paritoshtripathi935** [comment]
@nikhil25803 okay i can remove everything else except lxml. does that work?

**Pull request closed without merging**
