### PR TITLE
added following method

### PR DESCRIPTION
**Pull request by JatinGera27aug**

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey @JatinGera27aug, make sure you include the method in the `endpoints. md` file. Also, make a PR with some description from next time., like solving the issue, some screenshots, etc.

**Comment by JatinGera27aug** [comment]
noted. but I have mentioned the method in the documentation.md  as you suggested prior time

**Comment by nikhil25803** [comment]
> 

It is not reflected in the `documentation. md` as well as in file changes of the PR. Do check once.

**Comment by nikhil25803** [comment]
Hey @JatinGera27aug, I made some changes to the repository folder structure. Make a Git pull and and the method in the `users.py` of  GitHub.

**Comment by JatinGera27aug** [comment]
sure, just made a pr to commit my pending changes. thanks for the update

**Pull request closed without merging**
