### PR TITLE
GitHub test folder created

### PR DESCRIPTION
**Pull request by Mihan786Chistie**
## Description

> Created the GitHub test folder where all the test cases for each class are provided i.e., User, Repository, Issue, Pull Request and Organization.

## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [ ] Have you updated the 'documentation.md' file with the method/function documentation?
- [ ] Have you sent a message along with the result or response?
- [ ] Have you used the try-catch technique?
- [ ] Has the method/class been added to the documentation (md file)?

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by nikhil25803** [comment]
Great work @Mihan786Chistie !!
Do not forget to
+ Share your contribution on socials(twitter mainly), tag us and Clueless 🫂
+ Give this repository a star ✨
+ Follow Clueless Community on GitHub ✅

**Comment by Mihan786Chistie** [comment]
Thanks for the merge @nikhil25803. Can you level it up to level3? As it took a lot of effort and time. Please.

**Comment by nikhil25803** [comment]
It is mostly repetitive, which is why assigned level 2.

**Comment by Mihan786Chistie** [comment]
Ok👍

**Comment by Mihan786Chistie** [comment]
Hey @nikhil25803, do note that I got some errors while creating the test folder in some of the functions such as all_watcher() function for the Repository class and it returned that all_watcher() function was not available and similar for some other functions.

**Comment by nikhil25803** [comment]
Yes @Mihan786Chistie | Anyways I will refactor the entire code by next week for the next version launch, so will take a look at it the next time.

**Comment by Mihan786Chistie** [comment]
> Yes @Mihan786Chistie | Anyways I will refactor the entire code by next week for the next version launch, so will take a look at it the next time.

@nikhil25803 Do notify me for any extra help

**Pull request merged**
