### PR TITLE
Resolved the bug #271

### PR DESCRIPTION
**Pull request by karthikbhandary2**
So the methods were not working because the class name was changed in the users.py It was not updated in the __init__.py. So I changed the class name to its previous name `Users`. I don't know who but they just increased the lines of code by separately creating a method __parse_page(). I did not change that. Look at the changes and let me know if there is anything @nikhil25803

### CODE REVIEW

**Review by nikhil25803 — CHANGES_REQUESTED** [review]
+ Methods are still not working, please cross check once and do upload a SS also  for the output

image

**Comment by karthikbhandary2** [comment]
ok will look into it

**Comment by karthikbhandary2** [comment]
Hey @nikhil25803 I think I found out the reason why it is showing zero. The meta tag from which we are taking the data is showing that. I checked for the script tag as well and it is the same. When I use it on my profile it is showing fine. I think it has something to do with the website itself. I will check for other ways to get the data. (Don't close this as I am still looking for getting the data from other tags)

**Comment by nikhil25803** [comment]
Okay, take your time ✌️

**Comment by karthikbhandary2** [comment]
Hey @nikhil25803 I am still working on this. Need some time.

**Comment by nikhil25803** [comment]
No problem @karthikbhandary2

**Comment by karthikbhandary2** [comment]
Hey, @nikhil25803 Im almost done. Just wanted to confirm one thing. Is it ok if I create a single function in the Users class that gives the details of the user (posts, following, followers)? I think this works out best. If you can confirm I will make changes accordingly and push the code.

**Comment by nikhil25803** [comment]
Its okay, that works :))

**Comment by karthikbhandary2** [comment]
Ok, then I will get to it.

**Pull request closed without merging**
