### PR TITLE
added functions to retrieve the no. of repos and stars of a GitHub user

### PR DESCRIPTION
**Pull request by JatinGera27aug**
i have tried the code on around 15~20 ids, was working fine. pls let me know if any error occurs

### CODE REVIEW

**Comment by nikhil25803** [comment]
@JatinGera27aug, include these methods in the `endpoints.md` file.

**Comment by JatinGera27aug** [comment]
OK will do asap

**Comment by nikhil25803** [comment]
> may I know why these conflicts are arising back to back ??

GitHub restricts merging changes at the same block of the codebase.

**Comment by JatinGera27aug** [comment]
so any way to solve this? or we have to do it regularly over the time

**Comment by nikhil25803** [comment]
Hey @JatinGera27aug, closing this PR. Make a new one with proper changes.

**Pull request closed without merging**
