### PR TITLE
Added Scrapping data from Booking.com #1117

### LINKED ISSUE #1117: Feat:Scrapping data from Booking.com
### Describe the feature

As a part of GSSOC 24, I'd like to add a Booking.com module with the following functionalities:
https://www.booking.com/
We can get a lot of data based on location by scraping Booking.com like:
- hotel name 
-  price
- no. of rooms 
- facilities of the hotel
- reviews

### Add ScreenShots

Screenshot 2024-06-11 at 3 01 43 PM

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Anshika14528**
## Description

Added Booking.com module to give infromation about the hotels with their details of a place.

Usages
```py
from scrape_up import Booking.com
```

Create an instance of `BookingScraper` class

```python
scraper = BookingScraper("London")
```

| Method                   | Details                                                   |
| ------------------------ | --------------------------------------------------------- |
| `get_hotels()`           | Returns a list of hotels with their details.              |
---
## Checklist

> Before submitting this pull request, kindly verify that the ensuing checkpoints have been reached.

- [x] Have you adhered to the repository's defined coding convention rules?
- [x] Have you updated the 'documentation.md' file with the method/function documentation?
- [x] Have you sent a message along with the result or response?
- [x] Have you used the try-catch technique?
- [x] Has the method/class been added to the documentation (md file)?

## Screenshots

Screenshot 2024-08-03 at 5 46 07 PM

## Additional Notes/Comments

> Any additional remarks or suggestions concerning this pull request are welcome.

---

I certify that I have carried out the relevant checks and provided the requisite screenshot for validation by submitting this pull request.
I appreciate your contribution.

### CODE REVIEW

**Comment by Anshika14528** [comment]
@SudoSu-bham sir , please review it and merge it.

**Comment by Anshika14528** [comment]
@SudoSu-bham sir, please review and merge it please.

**Comment by SudoSu-bham** [comment]
cc @nikhil25803

**Comment by Anshika14528** [comment]
@nikhil25803 sir and @SudoSu-bham sir please review and merge it as program Is going to end.

**Pull request closed without merging**
