### PR TITLE
Issue #40 Commits made in a repository

### PR DESCRIPTION
**Pull request by ayushmorbar**
Added .commits() method which returns the number of commits made in a repository

### CODE REVIEW

**Comment by nikhil25803** [comment]
Hey @ayushmorbar, few points
+ We do not have to use APIs, we are building an API alternative using web scraping.
+ Add this method in the `Repository` class, you'll find that in the `/github` directory.
+  In the `Repository` class, use the private function to scrape the repository page and find an element containing the number of commits made in a repository.

**Comment by ayushmorbar** [comment]
Oh okay, lemme try it again

**Comment by nikhil25803** [comment]
Any update @ayushmorbar?

**Comment by ayushmorbar** [comment]
On it right now.

**Pull request merged**
